version: '3'

services:
  api:
    image: api:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '3000:3000'